### ISSUE TITLE
broken url?

### ISSUE THREAD

**Issue by Ariakim-Taiyo** [ADIBzTER/borang#3]
When I open the file generated by the script, i get this error:
```
src="https://www.gstatic.com/_/freebird/_/js/k=freebird.v.en_GB.R1Eb5tay5K8.O/d=1/rs=AMjVe6j1ltnjxRQ-AjHQ3Qw5hQ-t-P66vQ/m=viewer_base" nonce="FIsxRkw05YGCpraL85tcYg" type="16408c21848c1b91f89f9858-text/javascript">
File unavailable
```

The page freezes and none of the inputs or buttons work.

**Comment by Ariakim-Taiyo** [comment]
If i visit the websitre directly, i get a 404 error

**Comment by adibzter** [comment]
Hi there. I believe you're using https://borang.skrin.xyz & not the extension. Please use the [chrome extension](https://chrome.google.com/webstore/detail/borang/mokcmggiibmlpblkcdnblmajnplennol?hl=en-GB) since this is the only working way to submit multiple forms right now. If you're not using Chromium-based browser such as Firefox, not much I can help right now.

The website is outdated but I'm still trying to fix issues with the site.

**Comment by Ariakim-Taiyo** [comment]
Alright, thank you.
